version: '1.0'
services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app  # 로컬 디렉토리(프로젝트 루트)를 컨테이너의 /app 디렉토리에 마운트
      - /app/node_modules  # node_modules는 컨테이너 내에서 관리
    networks:
      - app-network
  backend:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./llm:/app  
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      port: 8081
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: password
      
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
